// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvSOMI3dascrlIMK0ntW2ie-81D0Sd7RQ',
    appId: '1:93436856937:web:ffc01bab175398a638b0f8',
    messagingSenderId: '93436856937',
    projectId: 'furnihunt',
    authDomain: 'furnihunt.firebaseapp.com',
    storageBucket: 'furnihunt.appspot.com',
    measurementId: 'G-JXM3HNVXGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzmGCJh4casyxovgPJrRHpPbcEkA8xVWQ',
    appId: '1:93436856937:android:8b78d3e275a0a68538b0f8',
    messagingSenderId: '93436856937',
    projectId: 'furnihunt',
    storageBucket: 'furnihunt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdn9SQCP8tmNOsWMN1uTe7G3Bt3PcgxlI',
    appId: '1:93436856937:ios:a6c6b3a0195102c238b0f8',
    messagingSenderId: '93436856937',
    projectId: 'furnihunt',
    storageBucket: 'furnihunt.appspot.com',
    iosBundleId: 'com.example.furniHunt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdn9SQCP8tmNOsWMN1uTe7G3Bt3PcgxlI',
    appId: '1:93436856937:ios:a971aabdbffe0bce38b0f8',
    messagingSenderId: '93436856937',
    projectId: 'furnihunt',
    storageBucket: 'furnihunt.appspot.com',
    iosBundleId: 'com.example.furniHunt.RunnerTests',
  );
}
